### ISSUE TITLE
Decodify fails to detect Base64 encoded string when lacking padding symbol if it could also be hex-encoded

### ISSUE THREAD

**Issue by alopresto** [UltimateHackers/Decodify#2]
The hex sequence `0x00 * 16` is Base64 encoded as `AAAAAAAAAAAAAAAAAAAAAA==` ('A' * 22). Some applications call for unpadded Base64 encoding (scrypt hashes, etc.). Decodify has trouble decoding strings which are Base64 encoded but lack the padding symbol, as it tries to interpret it as hex first. I thought this was because the string had an odd number of digits, but it appears to happen with even-numbered (i.e. valid hex string) as well. 

```
hw12203:/Users/alopresto/Workspace/Decodify (master) alopresto
🔓 161127s @ 12:21:01 $ dcode AAAAAAAAAAAAA # 'A' * 13 (arbitrary Base64 no padding)

    __                         __
  |/  |                   | / /
  |   | ___  ___  ___  ___|  (
  |   )|___)|    |   )|   )| |___ \   )
  |__/ |__  |__  |__/ |__/ | |     \_/
                                    /
Traceback (most recent call last):
  File "/usr/local/bin/dcode", line 180, in <module>
    decode(args.string)
  File "/usr/local/bin/dcode", line 160, in decode
    hexenc(string)
  File "/usr/local/bin/dcode", line 113, in hexenc
    string = bytearray.fromhex(string).decode()
ValueError: non-hexadecimal number found in fromhex() arg at position 12
hw12203:/Users/alopresto/Workspace/Decodify (master) alopresto
🔓 161151s @ 12:21:25 $ dcode AAAAAAAAAAAAAAAAAAAAAA # 'A' * 22 (Base64 no padding)

<banner redacted following>

Traceback (most recent call last):
  File "/usr/local/bin/dcode", line 180, in <module>
    decode(args.string)
  File "/usr/local/bin/dcode", line 160, in decode
    hexenc(string)
  File "/usr/local/bin/dcode", line 113, in hexenc
    string = bytearray.fromhex(string).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
hw12203:/Users/alopresto/Workspace/Decodify (master) alopresto
🔓 161184s @ 12:21:58 $ dcode AAAAAAAAAAAAAAAAAAAAAA== # 'A' * 22 + '=' * 2 (Base64 padding)

[+] Decoded from Base64 :
hw12203:/Users/alopresto/Workspace/Decodify (master) alopresto
🔓 161196s @ 12:22:10 $ dcode AAAAAAAAAAAA # 'A' * 12 (valid hex string)

Traceback (most recent call last):
  File "/usr/local/bin/dcode", line 180, in <module>
    decode(args.string)
  File "/usr/local/bin/dcode", line 160, in decode
    hexenc(string)
  File "/usr/local/bin/dcode", line 113, in hexenc
    string = bytearray.fromhex(string).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
hw12203:/Users/alopresto/Workspace/Decodify (master) alopresto
🔓 161372s @ 12:25:06 $ dcode AAAAAAAAAA # 'A' * 10 (valid hex string)

Traceback (most recent call last):
  File "/usr/local/bin/dcode", line 180, in <module>
    decode(args.string)
  File "/usr/local/bin/dcode", line 160, in decode
    hexenc(string)
  File "/usr/local/bin/dcode", line 113, in hexenc
    string = bytearray.fromhex(string).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
hw12203:/Users/alopresto/Workspace/Decodify (master) alopresto
🔓 161400s @ 12:25:34 $ dcode 30313233343536

[+] Decoded from Hex : 0123456
Traceback (most recent call last):
  File "/usr/local/bin/dcode", line 180, in <module>
    decode(args.string)
  File "/usr/local/bin/dcode", line 160, in decode
    hexenc(string)
  File "/usr/local/bin/dcode", line 115, in hexenc
    decode(string)
  File "/usr/local/bin/dcode", line 160, in decode
    hexenc(string)
  File "/usr/local/bin/dcode", line 113, in hexenc
    string = bytearray.fromhex(string).decode()
ValueError: non-hexadecimal number found in fromhex() arg at position 6
hw12203:/Users/alopresto/Workspace/Decodify (master) alopresto
🔓 161621s @ 12:29:15 $
```

**Comment by alopresto** [comment]
Is there a way to specify non-recursive operation? I like the simple operation of identifying the encoding scheme automatically, but there are many values which are only encoded once, but result in a "valid" encoding scheme after the first decode operation and the tool attempts to decode again and fails.

**Comment by UltimateHackers** [comment]
What we can do is to either change the order of checks for Base64 and hex or include an option to specify the encoding.

**Comment by alopresto** [comment]
I'm assuming it prioritizes hex first, and when the input is ambiguous, I understand it's difficult. Obviously checking the content for a non-hex character would allow you to identify that it is Base64, but if the input is actually valid in both, maybe present both possible outputs?

**Comment by UltimateHackers** [comment]
Yes we can do that.
